-- MySQL Script generated by MySQL Workbench
-- 08/06/18 21:40:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema la_jirafa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema la_jirafa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `la_jirafa` DEFAULT CHARACTER SET utf8 ;
USE `la_jirafa` ;

-- -----------------------------------------------------
-- Table `la_jirafa`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_jirafa`.`proveedor` (
  `rfc` VARCHAR(13) NOT NULL,
  `nombre_comp` VARCHAR(50) NOT NULL,
  `no_tel` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`rfc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `la_jirafa`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_jirafa`.`inventario` (
  `id` VARCHAR(4) NOT NULL,
  `color` TEXT NOT NULL,
  `marca` TEXT NOT NULL,
  `modelo` VARCHAR(15) NOT NULL,
  `nomb_desc` TEXT NOT NULL,
  `existencias` INT(10) UNSIGNED NOT NULL,
  `precio` DECIMAL(10,0) UNSIGNED NOT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rfc` (`rfc` ASC),
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`rfc`)
    REFERENCES `la_jirafa`.`proveedor` (`rfc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `la_jirafa`.`muebleria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_jirafa`.`muebleria` (
  `id_m` VARCHAR(4) NOT NULL,
  `color` TEXT NOT NULL,
  `marca` TEXT NOT NULL,
  `modelo` VARCHAR(15) NOT NULL,
  `nomb_desc` TEXT NOT NULL,
  `cantidad` INT(10) UNSIGNED NOT NULL,
  `precio` DECIMAL(10,0) UNSIGNED NOT NULL,
  `id` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_m`),
  INDEX `id` (`id` ASC),
  CONSTRAINT `muebleria_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `la_jirafa`.`inventario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `la_jirafa` ;

-- -----------------------------------------------------
-- Placeholder table for view `la_jirafa`.`info_prod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_jirafa`.`info_prod` (`id` INT, `marca` INT, `nomb_desc` INT, `rfc` INT);

-- -----------------------------------------------------
-- Placeholder table for view `la_jirafa`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `la_jirafa`.`productos` (`marca` INT, `nomb_desc` INT);

-- -----------------------------------------------------
-- procedure datos_prov
-- -----------------------------------------------------

DELIMITER $$
USE `la_jirafa`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `datos_prov`(rfc varchar(13))
select * from proveedor
where nombre_comp=rfc$$

DELIMITER ;

-- -----------------------------------------------------
-- View `la_jirafa`.`info_prod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `la_jirafa`.`info_prod`;
USE `la_jirafa`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `la_jirafa`.`info_prod` AS select `la_jirafa`.`inventario`.`id` AS `id`,`la_jirafa`.`inventario`.`marca` AS `marca`,`la_jirafa`.`inventario`.`nomb_desc` AS `nomb_desc`,`la_jirafa`.`inventario`.`rfc` AS `rfc` from `la_jirafa`.`inventario` where (`la_jirafa`.`inventario`.`id` like '5%');

-- -----------------------------------------------------
-- View `la_jirafa`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `la_jirafa`.`productos`;
USE `la_jirafa`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `la_jirafa`.`productos` AS select `la_jirafa`.`muebleria`.`marca` AS `marca`,`la_jirafa`.`muebleria`.`nomb_desc` AS `nomb_desc` from `la_jirafa`.`muebleria` where (`la_jirafa`.`muebleria`.`marca` = 'mabe');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
