/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package defaultpackage;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Edgar
 */
public class JFBorrar extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;
    private ResultSet rs;
    
    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/la_jirafa", "root", "");
            st = conexion.createStatement();
            rs = st.executeQuery("Select * from usuario;");
            moverPrimerRegistro();
            deshabilitarEdicion();
        } catch (SQLException ex) {
            cancelar();
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos" + ex.getMessage());
        }
    }
    public void moverPrimerRegistro() {
        try {
            rs.first();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    public void moverRegistroSiguiente() {
        try {
            if (!rs.isLast()) {
                rs.next();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    public void moverRegistroAnterior() {
        try {
            if (!rs.isFirst()) {
                rs.previous();
                llenarDatos();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 001" + ex.getMessage());
        }
    }
    public void moverUltimoRegistro() {
        try {
            rs.last();
            llenarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error mover ultimo registro" + ex.getMessage());
        }
    }
    public void llenarDatos() {
        try {
            this.jtf_nombre.setText(rs.getString("usuario"));
            this.jtf_tipo.setText(rs.getString("tipo"));
            deshabilitarEdicion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error llenar datos" + ex.getMessage());
        }
    }
    public void deshabilitarEdicion(){
        jtf_tipo.setEditable(false);
        jtf_nombre.setEditable(false);
        }
    private void borrarRegistro(){
        try{ 
            String nombre=this.jtf_nombre.getText();
            int resp=JOptionPane.showConfirmDialog(null,"Esta seguro de que desea eliminar el usuario seleccionado?");
            if (JOptionPane.OK_OPTION == resp){
                st.executeUpdate("delete from proveedor where nombre='"+nombre+"';");
                JOptionPane.showMessageDialog(this,"Usuario Eliminado" );
                Conectar();
            }
        } catch(SQLException err){ 
             JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
         } 
    } 
    public void desactivarBorrar(){
        JFBorrar jfborrar=new JFBorrar();
        jfborrar.setVisible(false);
        }
    public void activarMenu(){
        JFMenu jfmenu=new JFMenu();
        jfmenu.setVisible(true);
        this.setVisible(false);
        }
    public void cancelar(){
        activarMenu();
        desactivarBorrar();
    }
    /**
     * Creates new form JFBorrar
     */
    public JFBorrar() {
        initComponents();
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_nombre = new javax.swing.JTextField();
        jtf_tipo = new javax.swing.JTextField();
        jl_nombre = new javax.swing.JLabel();
        jf_tipo = new javax.swing.JLabel();
        jp_botonesn = new javax.swing.JPanel();
        jb_registro_anterior = new javax.swing.JButton();
        jb_primer_registro = new javax.swing.JButton();
        jb_registro_siguiente = new javax.swing.JButton();
        jb_ultimo_registro = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jl_nombre.setText("Nombre del usuario:");

        jf_tipo.setText("Tipo");

        jb_registro_anterior.setText("<<");
        jb_registro_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registro_anteriorActionPerformed(evt);
            }
        });

        jb_primer_registro.setBackground(new java.awt.Color(255, 255, 255));
        jb_primer_registro.setText("|<");
        jb_primer_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_primer_registroActionPerformed(evt);
            }
        });

        jb_registro_siguiente.setText(">>");
        jb_registro_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registro_siguienteActionPerformed(evt);
            }
        });

        jb_ultimo_registro.setText(">|");
        jb_ultimo_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ultimo_registroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_botonesnLayout = new javax.swing.GroupLayout(jp_botonesn);
        jp_botonesn.setLayout(jp_botonesnLayout);
        jp_botonesnLayout.setHorizontalGroup(
            jp_botonesnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_botonesnLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jb_primer_registro)
                .addGap(57, 57, 57)
                .addComponent(jb_registro_anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jb_registro_siguiente)
                .addGap(66, 66, 66)
                .addComponent(jb_ultimo_registro)
                .addGap(41, 41, 41))
        );
        jp_botonesnLayout.setVerticalGroup(
            jp_botonesnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_botonesnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_botonesnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_registro_anterior)
                    .addComponent(jb_primer_registro)
                    .addComponent(jb_registro_siguiente)
                    .addComponent(jb_ultimo_registro))
                .addContainerGap())
        );

        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp_botonesn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_nombre)
                            .addComponent(jf_tipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_nombre)
                            .addComponent(jtf_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jb_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jf_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_botonesn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_borrar)
                    .addComponent(jb_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void jb_registro_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registro_anteriorActionPerformed
        moverRegistroAnterior();
    }//GEN-LAST:event_jb_registro_anteriorActionPerformed

    private void jb_primer_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_primer_registroActionPerformed
        moverPrimerRegistro();
    }//GEN-LAST:event_jb_primer_registroActionPerformed

    private void jb_registro_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registro_siguienteActionPerformed
        moverRegistroSiguiente();
    }//GEN-LAST:event_jb_registro_siguienteActionPerformed

    private void jb_ultimo_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ultimo_registroActionPerformed
        moverUltimoRegistro();
    }//GEN-LAST:event_jb_ultimo_registroActionPerformed

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarMouseClicked
        borrarRegistro();
    }//GEN-LAST:event_jb_borrarMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        cancelar();
    }//GEN-LAST:event_jb_cancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBorrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBorrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_primer_registro;
    private javax.swing.JButton jb_registro_anterior;
    private javax.swing.JButton jb_registro_siguiente;
    private javax.swing.JButton jb_ultimo_registro;
    private javax.swing.JLabel jf_tipo;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JPanel jp_botonesn;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_tipo;
    // End of variables declaration//GEN-END:variables
}
