

package defaultpackage;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Abi Montes
 */
public class JFLogin extends javax.swing.JFrame {
  private Connection conexion;
    private Statement st;
    private ResultSet rs;
    
    public void conectar(){
        try{
        conexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/la_jirafa","root","");
            st=conexion.createStatement();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null,"Error"+err.getMessage());
        }
    }
    /**
     * Creates new form logi
     */
    public JFLogin() {
        initComponents();
        this.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_usuario = new javax.swing.JLabel();
        jl_contra = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jb_iniciar = new javax.swing.JButton();
        JB_cancelar = new javax.swing.JButton();
        jfp_contra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_usuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jl_usuario.setForeground(new java.awt.Color(0, 204, 51));
        jl_usuario.setText("USUARIO");

        jl_contra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jl_contra.setForeground(new java.awt.Color(0, 204, 51));
        jl_contra.setText("CONTRASEÑA");

        jtf_usuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usuarioActionPerformed(evt);
            }
        });

        jb_iniciar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jb_iniciar.setText("INICIAR");
        jb_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarMouseClicked(evt);
            }
        });

        JB_cancelar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        JB_cancelar.setForeground(new java.awt.Color(255, 51, 51));
        JB_cancelar.setText("CANCELAR");
        JB_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_cancelarMouseClicked(evt);
            }
        });

        jfp_contra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIO DE SESIÓN ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_contra)
                    .addComponent(jl_usuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_usuario)
                    .addComponent(jfp_contra))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jb_iniciar)
                .addGap(81, 81, 81)
                .addComponent(JB_cancelar)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_usuario)
                    .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_contra)
                    .addComponent(jfp_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_iniciar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB_cancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usuarioActionPerformed

    private void JB_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_cancelarMouseClicked
    this.setVisible(false);        
    }//GEN-LAST:event_JB_cancelarMouseClicked

    private void jb_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarMouseClicked
               String usuario=jtf_usuario.getText();
               String contra=String.valueOf(jfp_contra.getPassword());
         try{
           rs=st.executeQuery("select count(usuario) as existe from usuario where usuario='"+usuario+"' and contra='"+contra+"';");
           rs.first();
           int Existe;
           String existe=rs.getString("existe");
           Existe=Integer.parseInt(existe);
           if (Existe==1){
               JFMenu jfmenu=new JFMenu();
               jfmenu.setVisible(true);
               this.setVisible(false);
           }
           else{
               JOptionPane.showMessageDialog(null,"No coinciden");
               JFLogin jf_login=new JFLogin();
               jf_login.setVisible(true);
               this.setVisible(false);
           }
         } catch(SQLException err){ 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        } 
    }//GEN-LAST:event_jb_iniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_iniciar;
    private javax.swing.JPasswordField jfp_contra;
    private javax.swing.JLabel jl_contra;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
