/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package defaultpackage;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.JOptionPane;

public class JFMenu extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;
    private ResultSet rs;
    
    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/la_jirafa", "root", "");
            st = conexion.createStatement();
            rs = st.executeQuery("Select * from usuario;");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos" + ex.getMessage());
        }
    }
    public void activarLogin(){
        JFLogin jflogin=new JFLogin();
        jflogin.setVisible(true);
        this.setVisible(false);
    }
    public void crearNuevo(){
        JFCuenta jfcuenta=new JFCuenta();
        jfcuenta.setVisible(true);
        this.setVisible(false);
    }

  /*  public void cerrarProveedores(){
        JFrame Proveedores=new JFrame();
        proveedores.getContentpane().add(panel,borderLayout.CENTER);
        proveedores.addWindowListener(new WindowAdapter(){
            public void WindowClosing(WindowEvent evt){
                System.exit(0);
            }
        });
    }
    /**
     * Creates new form menu
     */
    public JFMenu() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_proveedor = new javax.swing.JButton();
        jb_venta = new javax.swing.JButton();
        jb_inventario = new javax.swing.JButton();
        jb_Nuevo = new javax.swing.JButton();
        jb_Cerrar_sesion = new javax.swing.JButton();
        jb_borrarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_proveedor.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jb_proveedor.setForeground(new java.awt.Color(102, 204, 0));
        jb_proveedor.setText("PROVEEDORES");
        jb_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_proveedorMouseClicked(evt);
            }
        });
        jb_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_proveedorActionPerformed(evt);
            }
        });

        jb_venta.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jb_venta.setForeground(new java.awt.Color(0, 204, 255));
        jb_venta.setText("VENTAS ");
        jb_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ventaMouseClicked(evt);
            }
        });
        jb_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ventaActionPerformed(evt);
            }
        });

        jb_inventario.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jb_inventario.setForeground(new java.awt.Color(255, 0, 0));
        jb_inventario.setText("INVENTARIO");
        jb_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_inventarioMouseClicked(evt);
            }
        });
        jb_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inventarioActionPerformed(evt);
            }
        });

        jb_Nuevo.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jb_Nuevo.setForeground(new java.awt.Color(0, 204, 255));
        jb_Nuevo.setText("Crear Nuevo Usuario");
        jb_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_NuevoMouseClicked(evt);
            }
        });
        jb_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_NuevoActionPerformed(evt);
            }
        });

        jb_Cerrar_sesion.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jb_Cerrar_sesion.setForeground(new java.awt.Color(0, 204, 255));
        jb_Cerrar_sesion.setText("Cerrar sesión");
        jb_Cerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Cerrar_sesionMouseClicked(evt);
            }
        });
        jb_Cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Cerrar_sesionActionPerformed(evt);
            }
        });

        jb_borrarUsuario.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jb_borrarUsuario.setForeground(new java.awt.Color(0, 204, 255));
        jb_borrarUsuario.setText("Borrar Usuario");
        jb_borrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarUsuarioMouseClicked(evt);
            }
        });
        jb_borrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_proveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jb_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Cerrar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jb_proveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_inventario)
                .addGap(18, 18, 18)
                .addComponent(jb_venta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_Cerrar_sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_Nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_borrarUsuario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_proveedorActionPerformed
    }//GEN-LAST:event_jb_proveedorActionPerformed
    private void jb_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ventaActionPerformed
    }//GEN-LAST:event_jb_ventaActionPerformed
    private void jb_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inventarioActionPerformed
    }//GEN-LAST:event_jb_inventarioActionPerformed
    private void jb_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_proveedorMouseClicked
        JFProveedores jfproveedores = new JFProveedores();
        jfproveedores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_proveedorMouseClicked

    private void jb_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_inventarioMouseClicked
        JFJirafita jf_jirafita = new JFJirafita();
        jf_jirafita.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_inventarioMouseClicked

    private void jb_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ventaMouseClicked
        JFVentas jfventas = new JFVentas();
        jfventas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_ventaMouseClicked

    private void jb_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_NuevoMouseClicked
        crearNuevo();
    }//GEN-LAST:event_jb_NuevoMouseClicked

    private void jb_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_NuevoActionPerformed
    }//GEN-LAST:event_jb_NuevoActionPerformed
    private void jb_Cerrar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Cerrar_sesionMouseClicked
            int resp=JOptionPane.showConfirmDialog(null,"Desea Cerrar sesión?");
            if (JOptionPane.OK_OPTION == resp){
                activarLogin();
            }
    }//GEN-LAST:event_jb_Cerrar_sesionMouseClicked
    private void jb_Cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Cerrar_sesionActionPerformed
    }//GEN-LAST:event_jb_Cerrar_sesionActionPerformed

    private void jb_borrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarUsuarioMouseClicked
        JFBorrar jfborrar = new JFBorrar();
        jfborrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_borrarUsuarioMouseClicked

    private void jb_borrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_borrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Cerrar_sesion;
    private javax.swing.JButton jb_Nuevo;
    private javax.swing.JButton jb_borrarUsuario;
    private javax.swing.JButton jb_inventario;
    private javax.swing.JButton jb_proveedor;
    private javax.swing.JButton jb_venta;
    // End of variables declaration//GEN-END:variables
}
